import type { Speaker } from "../types/speaker";

export const FEATURED_SPEAKERS: Speaker[] = [
  {
    name: "Don Ward",
    role: "Customer Engineer Specialist",
    company: "Google",
    imageUrl: "/don-ward.webp",
    imageAlt: "Don Ward",
    linkedinUrl: "https://www.linkedin.com/in/donwardpeng/",
    accentColor: "blue",
    bio: "Don Ward is a cloud enthusiast and Customer Engineer at Google Cloud, bringing deep practical experience to the table. In the last 5 years alone, he's earned an impressive 17 cloud certifications across Google and AWS, fueled by a passion for continuous learning and a drive to master the Google Cloud ecosystem. Don's commitment extends to the local tech scene, where he's spent 12 years fostering growth by leading Google Developer Groups in Windsor and Detroit. While transitioning leadership, he remains a dedicated volunteer, empowering others to lead.",
  },
  {
    name: "Keval Patel",
    role: "Founder & AI Educator",
    company: "Architecttura Inc., Architects",
    imageUrl: "/keval-patel.webp",
    imageAlt: "Keval Patel",
    linkedinUrl: "https://www.linkedin.com/in/kmpatel100/",
    accentColor: "green",
    bio: "Keval Patel is a Founder & AI Educator at Architecttura Inc., designing enterprise IT solutions and fostering the next generation of tech professionals.",
  },
  {
    name: "Elvis Akhalu",
    role: "Data Engineer",
    company: "TD",
    imageUrl: "/elvis-akhalu.webp",
    imageAlt: "Elvis Akhalu",
    linkedinUrl: "https://www.linkedin.com/in/elvisakhalu/",
    accentColor: "red",
    bio: "Elvis Akhalu is a Data Engineer at TD, building robust data pipelines and analytics infrastructure for financial services.",
  },
  {
    name: "Joe Youssouf",
    role: "Lead Customer Data Scientist",
    company: "Oden Technologies",
    imageUrl: "/joe-youssouf.webp",
    imageAlt: "Joe Youssouf",
    linkedinUrl: "https://www.linkedin.com/in/joeyoussouf/",
    accentColor: "gold",
    bio: "Joe Youssouf is a Lead Customer Data Scientist at Oden Technologies, leveraging AI and machine learning to solve complex business challenges.",
  },
  {
    name: "Arunesh Choudhary",
    role: "Conversational AI Engineer",
    company: "Dialabot.ai",
    imageUrl: "/arunesh-choudhary.webp",
    imageAlt: "Arunesh Choudhary",
    linkedinUrl: "https://www.linkedin.com/in/aruneshchoudhary/",
    accentColor: "blue",
    bio: "As a Conversational AI Engineer at Dialabot.ai, I design, develop, and deploy scalable conversational AI agents tailored to business needs. I architect conversation flows, configure agent behaviors, and integrate agents with CRMs, APIs, calendars, and enterprise systems to automate workflows and improve user interactions. I also build and maintain data pipelines to support agent training, performance monitoring, and continuous optimization, ensuring reliable and production-ready AI solutions.",
  },
  {
    name: "Umair Durrani",
    role: "Data Scientist",
    company: "Presage Group",
    imageUrl: "/umair-durrani.jpg",
    imageAlt: "Umair Durrani",
    linkedinUrl: "https://www.linkedin.com/in/durraniu/",
    accentColor: "green",
    bio: "Umair Durrani is a Data Scientist at Presage Group Inc., where he conducts scientific studies in the field of human factors and decision-making. Umair also develops web applications and data tools for optimizing data collection and reporting. With a PhD in Civil Engineering, he is passionate about modeling and mitigating human error in transportation systems. Umair also teaches data analysis workshops and frequently gives talks on topics such as R programming, Shiny apps, and open-source tools for transportation research.",
  },
  {
    name: "Troy Hector",
    role: "Client Data Analyst II",
    company: "Mosaic North America",
    imageUrl: "/troy-hector.webp",
    imageAlt: "Troy Hector",
    linkedinUrl: "https://www.linkedin.com/in/itroyhector/",
    accentColor: "red",
    bio: "Troy Hector is a full-stack developer with more than 10 years of experience. After studying at St. Clair College, he now works as a Client Data Analyst II at Mosaic North America, supporting Google.",
  },
  {
    name: 'Steven Rice',
    role: 'Automation Specialist',
    company: 'DataRealm',
    imageUrl: '/Steven-Rice.webp',
    imageAlt: 'Steven Rice',
    linkedinUrl: 'https://www.linkedin.com/in/stevenrice99/',
    accentColor: 'blue',
    bio: 'Steven Rice is an Automation Specialist at DataRealm and a Computer Science PhD candidate at the University of Windsor. He works across physical AI, simulation, robotics, vision-language-action systems, and digital twins. He has also taught game development and built tools for Unity simulations and networking.',
  },
  {
    name: 'Florid Maclean',
    role: 'CEO & Professor',
    company: 'Catch The Event | Fanshawe College',
    imageUrl: '/florid-maclean.webp',
    imageAlt: 'Florid Maclean',
    linkedinUrl: 'https://www.linkedin.com/in/florid-maclean',
    accentColor: 'green',
    bio: 'Florid Maclean is a Professor at Fanshawe College, software consultant, and founder of PORT24 Technologies Inc. and Catch The Event. He mentors emerging innovators with a practical founder perspective and helps lead Google Developer Groups London.',
  },
  {
    name: 'Sandra Lopez-Zamora',
    role: 'Senior Manager - Data Strategy and Analytics',
    company: 'Scotiabank',
    imageUrl: '/sandra-lopez.webp',
    imageAlt: 'Sandra Lopez-Zamora',
    linkedinUrl: 'https://www.linkedin.com/in/slopezza/',
    accentColor: 'red',
    bio: 'Sandra Lopez-Zamora is a Senior Manager in Global Risk Management at Scotiabank and the City Lead for Women in AI London. Her work includes cloud migration, credit risk modeling, and data strategy, and she supports women in tech and newcomers to Canada.',
  },
  {
    name: 'Diaa ElKott',
    role: 'Senior Software Engineer',
    company: 'ISRA VISION - Part of Atlas Copco',
    imageUrl: '/Diaa-ElKott.webp',
    imageAlt: 'Diaa ElKott',
    linkedinUrl: 'https://www.linkedin.com/in/elkott/',
    accentColor: 'gold',
    bio: 'Diaa ElKott is a mechanical engineer and software developer with a PhD in Mechanical Engineering from McMaster University. He builds software for industrial measurement using geometric modeling and computer vision.',
  },
  {
    name: 'Kylie Kiser',
    role: 'Owner',
    company: 'Kylie K Consulting',
    imageUrl: '/kylie-kiser.webp',
    imageAlt: 'Kylie Kiser',
    linkedinUrl: 'https://www.linkedin.com/in/kylie-kiser/',
    accentColor: 'blue',
    bio: 'Kylie Kiser is a Microsoft Business Applications MVP and Fast Track Recognized Solution Architect. Through Kylie K Consulting, she helps teams build secure, scalable solutions with Dynamics 365, Dataverse, and the Power Platform. She also teaches and speaks at community events.',
  },
  {
    name: 'Andrea Irina Yzeiri',
    role: 'Chief Data & Analytics Officer and Lead AI Engineer',
    company: 'Picsume',
    imageUrl: '/andrea-irina.webp',
    imageAlt: 'Andrea Irina Yzeiri',
    linkedinUrl: 'https://www.linkedin.com/in/andrea-yzeiri/',
    accentColor: 'green',
    bio: 'Andrea Irina Yzeiri leads data and AI innovation at Picsume, with a focus on responsible AI, bias mitigation, accountability, and governance. Her experience spans analytics, cybersecurity for AI systems, research, and technology leadership. She also teaches Python and analytics workshops.',
  },
  {
    name: 'Mina Girges',
    role: 'Vice President & Chief Information Officer',
    company: 'TransForm Shared Service Organization',
    imageUrl: '/mina-girges.webp',
    imageAlt: 'Mina Girges',
    linkedinUrl: 'https://www.linkedin.com/in/minagirges/',
    accentColor: 'red',
    bio: 'Mina Girges is an award-winning information systems leader and IT strategist. As Vice President and Chief Information Officer at TransForm Shared Service Organization, he focuses on Zero Trust, digital transformation, and secure, scalable infrastructure.',
  },
  {
    name: 'Amrit Mehta',
    role: 'Senior Advisor',
    company: 'Deloitte',
    imageUrl: '/amrit-mehta.webp',
    imageAlt: 'Amrit Mehta',
    linkedinUrl: 'https://www.linkedin.com/in/amritmehta/',
    accentColor: 'gold',
    bio: 'Amrit Mehta has spent 30 years in leadership roles across the automotive, mobility, and technology sectors. His work includes digital transformation, electric and connected vehicles, direct-to-consumer experiences, operations, and strategy.',
  },
  {
    name: 'Frank Abbruzzese',
    role: 'CEO & President',
    company: 'AlphaKOR',
    imageUrl: '/frank-abbruzzes.webp',
    imageAlt: 'Frank Abbruzzese',
    linkedinUrl: 'https://www.linkedin.com/in/frankabbruzzese/',
    accentColor: 'blue',
    bio: 'Frank Abbruzzese is President of AlphaKOR and has more than 37 years of experience in technology. He builds long-term relationships, advises organizations on technology strategy, mentors business leaders, and is the author of Building Legacies.',
  },
  {
    name: 'Veronica Reingold',
    role: 'Computer Science Student',
    company: 'University of Windsor',
    imageUrl: '/veronica-reingo.webp',
    imageAlt: 'Veronica Reingold',
    linkedinUrl: 'https://www.linkedin.com/in/veronicareingold/',
    accentColor: 'green',
    bio: 'Veronica Reingold researches AI applications for video game accessibility as a Computer Science MSc student. Her work brings together game development, creative uses of AI, and more accessible experiences for players.',
  },
  {
    name: 'Wen Teoh',
    role: 'President & Principal Consultant',
    company: 'Good Point Consulting',
    imageUrl: '/wen-teoh.webp',
    imageAlt: 'Wen Teoh',
    linkedinUrl: 'https://www.linkedin.com/in/wen-teoh/',
    accentColor: 'red',
    bio: 'Wen Teoh is President and Principal Consultant at Good Point Consulting. With more than 20 years of experience in leadership, startups, project management, and operations, she has helped build inclusive entrepreneurship programs and secure funding for regional innovators.',
  },
  {
    name: 'Sean Bridgeman',
    role: 'Director of Product Management',
    company: 'HALIGHT Inc',
    imageUrl: '/sean-bridgeman.webp',
    imageAlt: 'Sean Bridgeman',
    linkedinUrl: 'https://www.linkedin.com/in/sean-bridgeman-b2a30a178/',
    accentColor: 'gold',
    bio: 'Sean Bridgeman is a product leader focused on building collaborative teams and product cultures that deliver value.',
  },
  {
    name: 'Camila Gaitan',
    role: 'Systems Engineer | Business Data Analyst',
    company: 'Softgic',
    imageUrl: '/camila-gaitan.jpeg',
    imageAlt: 'Camila Gaitan',
    linkedinUrl: 'https://www.linkedin.com/in/lizeth-camila-gaitan-baron/',
    accentColor: 'blue',
    bio: 'Camila Gaitan is a Systems Engineer with more than eight years of experience leading digital and software projects. She has worked as a Project Lead, Scrum Master, and Project Manager, bringing an end-to-end view of product development.',
  },
  {
    name: 'Kevin Serrano Mojica',
    role: 'Software Engineer | Android Developer',
    company: 'Mercado Libre',
    imageUrl: '/kevin_serrano.webp',
    imageAlt: 'Kevin Serrano Mojica',
    linkedinUrl: 'https://www.linkedin.com/in/kevinserranomojica/',
    accentColor: 'green',
    bio: 'Kevin Serrano Mojica is a software developer with more than seven years of experience, specializing in native Android development with Kotlin, Jetpack Compose, Java, Firebase, and Google Mobile Services. He also has experience with Swift and SwiftUI for iOS.',
  },
  {
    name: 'Vimal K.',
    role: 'Co-Founder',
    company: 'GDG Cloud Toronto',
    imageUrl: '/vimal-k.webp',
    imageAlt: 'Vimal K.',
    accentColor: 'red',
  },
];
