import type { Speaker } from "../types/speaker";

export const FEATURED_SPEAKERS: Speaker[] = [
  // KEYNOTE SPEAKERS (Featured - First 4)
  {
    name: "Don Ward",
    role: "Customer Engineer Specialist",
    company: "Google",
    imageUrl: "/don-ward.webp",
    imageAlt: "Don Ward",
    linkedinUrl: "https://www.linkedin.com/in/donwardpeng/",
    accentColor: "blue",
    bio: "Don Ward is a cloud enthusiast and Customer Engineer at Google Cloud, bringing deep practical experience to the table. In the last 5 years alone, he's earned an impressive 17 cloud certifications across Google and AWS, fueled by a passion for continuous learning and a drive to master the Google Cloud ecosystem. Don's commitment extends to the local tech scene, where he's spent 12 years fostering growth by leading Google Developer Groups in Windsor and Detroit. While transitioning leadership, he remains a dedicated volunteer, empowering others to lead.",
  },
  {
    name: "Keval Patel",
    role: "Founder & AI Educator",
    company: "Architecttura Inc., Architects",
    imageUrl: "/keval-patel.webp",
    imageAlt: "Keval Patel",
    linkedinUrl: "https://www.linkedin.com/in/kmpatel100/",
    accentColor: "green",
    bio: "Keval Patel is an educator, AI enthusiast, and founder of REALIQ, helping businesses and learners harness AI, automation, and cloud solutions through practical, hands-on training. He specializes in multi-agent AI workflows, low-code automation tools, and self-hosted systems, with a focus on turning complex technology into real-world results.",
  },
  {
    name: "Elvis Akhalu",
    role: "Data Engineer",
    company: "TD",
    imageUrl: "/elvis-akhalu.webp",
    imageAlt: "Elvis Akhalu",
    linkedinUrl: "https://www.linkedin.com/in/elvisakhalu/",
    accentColor: "red",
    bio: "Elvis Akhalu is a data professional working as a Data Engineer at TD Bank and holds a Master's degree in Business Data Analytics. He is proficient in data architecture, engineering, and modern tool stacks including Azure Databricks, Python, and cloud technologies. Beyond his work with financial data systems, Elvis serves as a Chapter Leader at Black Boys Code Windsor, where he mentors the next generation of tech talent and creates hands-on learning opportunities for youth in the local community.",
  },
  {
    name: "Joe Youssouf",
    role: "Lead Customer Data Scientist",
    company: "Oden Technologies",
    imageUrl: "/joe-youssouf.webp",
    imageAlt: "Joe Youssouf",
    linkedinUrl: "https://www.linkedin.com/in/joeyoussouf/",
    accentColor: "gold",
    bio: "Joe Youssouf is the Lead Customer Data Scientist at Oden Technologies, where he develops AI-powered solutions that deliver real-time, domain-specific intelligence to manufacturing. His work on ProcessAI delivers real-time control recommendations that reduce waste, increase throughput, and enhance safety across global operations. Prior to Oden, he scaled predictive maintenance systems for over 15,000 heavy-duty vehicles at Preteckt, where his models saved thousands in annual maintenance costs per vehicle. With a background in electrical and computer engineering and a strong foundation in statistics, Joe combines deep technical expertise with practical, real-world impact. He has helped organizations avoid costly infrastructure mistakes, reduce energy waste, and build data systems that support critical business decisions.",
  },
  
  // ORGANIZERS & FACILITATORS (Show after "View all speakers")
  {
    name: "Ali El-Sharif",
    role: "Professor",
    company: "St. Clair College",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    imageAlt: "Ali El-Sharif",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "blue",
    bio: "Ali El-Sharif is a Professor at St. Clair College and one of the key organizers of GDG Windsor DevFest 2026.",
  },
  {
    name: "Vivian Tang",
    role: "Data Consultant",
    company: "BDO",
    imageUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    imageAlt: "Vivian Tang",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "green",
    bio: "Vivian Tang is a Data Consultant at BDO with expertise in data analytics and business intelligence.",
  },
  {
    name: "Daria Deriagina",
    role: "Developer",
    company: "DashDev",
    imageUrl: "https://randomuser.me/api/portraits/women/2.jpg",
    imageAlt: "Daria Deriagina",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "red",
    bio: "Daria is a talented developer at DashDev and an organizer of GDG Windsor.",
  },
  {
    name: "Ron Mckenzie",
    role: "Teacher",
    company: "Greater Essex County District School Board",
    imageUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    imageAlt: "Ron Mckenzie",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "gold",
    bio: "Ron Mckenzie is an educator and facilitator dedicated to inspiring the next generation of tech professionals.",
  },
  {
    name: "Rob Chaykoski",
    role: "Lead Security Engineer",
    company: "Ontario Health",
    imageUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    imageAlt: "Rob Chaykoski",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "blue",
    bio: "Rob Chaykoski is a Lead Security Engineer at Ontario Health, specializing in healthcare cybersecurity.",
  },
  {
    name: "Esraa Abdelhalim",
    role: "Assistant Professor",
    company: "University of Windsor",
    imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    imageAlt: "Esraa Abdelhalim",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "green",
    bio: "Esraa Abdelhalim is an Assistant Professor at the University of Windsor, conducting research in computer science.",
  },
  {
    name: "Ashlynn Ward",
    role: "Computer Science Student",
    company: "University of Windsor",
    imageUrl: "https://randomuser.me/api/portraits/women/4.jpg",
    imageAlt: "Ashlynn Ward",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "red",
    bio: "Ashlynn Ward is a passionate Computer Science student at the University of Windsor.",
  },
  {
    name: "ranem ghalion",
    role: "AI Engineer",
    company: "Hackforge",
    imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
    imageAlt: "ranem ghalion",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "gold",
    bio: "ranem ghalion is an AI Engineer at Hackforge, working on innovative AI solutions.",
  },
  {
    name: "Arunesh Choudhary",
    role: "Conversational AI Engineer",
    company: "Dialabot.ai",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    imageAlt: "Arunesh Choudhary",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "blue",
    bio: "Arunesh Choudhary specializes in conversational AI and natural language processing.",
  },
  {
    name: "Sam Ghasan",
    role: "Enterprise Architect",
    company: "Tech Solutions",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    imageAlt: "Sam Ghasan",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "green",
    bio: "Sam Ghasan is an Enterprise Architect designing scalable solutions for complex organizational challenges.",
  },
  {
    name: "Kiran Puthan",
    role: "Solution Consultant",
    company: "Ordway Labs",
    imageUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    imageAlt: "Kiran Puthan",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "red",
    bio: "Kiran Puthan is a Solution Consultant at Ordway Labs, helping organizations implement effective technology solutions.",
  },
];
